### ISSUE TITLE
dict object' has no attribute 'dcos_bootstrap_iface'

### ISSUE THREAD

**Issue by kenadet** [andrewrothstein/ansible-dcos-deploy#4]
Hello, 

I got this error when I executed the role: 

failed: [192.168.1.217] (item=genconf/config.yaml) => {"failed": true, "item": "genconf/config.yaml", "msg": "AnsibleUndefinedVariable: http://{{ hostvars[groups[dcos_bootstrap_group][0]]['ansible_' + hostvars[groups[dcos_bootstrap_group][0]]['dcos_bootstrap_iface']]['ipv4']['address'] }}:{{dcos_bootstrap_port}}: 'dict object' has no attribute 'dcos_bootstrap_iface'"}

There is something with the dcos_bootstrap_iface.

**Comment by andrewrothstein** [comment]
I usually set the dcos_bootstrap_iface var at either the host or group level. How have you set it in your setup?

**Comment by kenadet** [comment]
I set it up in group_vars/all or main.yml in defaults, but I am more interested in what value this represent, and what value it should hold. Could it be 'ansible_eth0' or 'eth0'?

**Comment by andrewrothstein** [comment]
it should be the name of the interface 'eth0'. when Ansible gathers facts it creates an entry in the hostvars that looks like 'ansible_eth0'. is it possible that the network adapter you want to expose the bootstrap container through is on an interface other than eth0? perhaps it's enp0s8? try running `ifconfig -a` on the machine.

**Comment by kenadet** [comment]
Here is the result of my ifconfig -a, still get the same result trying the interface.

''' docker0   Link encap:Ethernet  HWaddr 02:42:35:48:21:ca  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:4a:55:b6  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe4a:55b6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:107443 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49944 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:88539423 (88.5 MB)  TX bytes:3072788 (3.0 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:ee:37:51  
          inet addr:192.168.1.217  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feee:3751/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2623 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1429 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1305040 (1.3 MB)  TX bytes:184058 (184.0 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
'''

**Comment by andrewrothstein** [comment]
eth0 or eth1 should work just fine as the interface. try `ansible -i localhost, -m setup localhost` to see what facts Ansible is gathering for the host. you should see ansible_eth0 and ansible_eth1 in the facts.

**Comment by kenadet** [comment]
I actually tried `ansible_eth0`, and got this:

failed: [192.168.1.217](item=/root/dcos-bootstrap/dcos_generate_config.sh) => {"changed": true, "cmd": ["/root/dcos-bootstrap/dcos_generate_config.sh"], "delta": "0:00:27.092508", "end": "2016-11-01 03:52:36.378113", "failed": true, "item": "/root/dcos-bootstrap/dcos_generate_config.sh", "rc": 1, "start": "2016-11-01 03:52:09.285605", "stderr": "\u001b[33m====> EXECUTING CONFIGURATION GENERATIONExecute the configuration generation (genconf).\u001b[0m\nGenerating configuration files...\n\u001b[1;31mmaster_list: List cannot contain duplicates: 10.0.2.15 appears 3 times\u001b[0m", "stdout": "Extracting image from this script and loading into docker daemon, this step can take a few minutes\ndcos-genconf.cfccfbf84bbba30e69-405172d16eaff8798d.tar\nLoaded image: mesosphere/dcos-genconf:cfccfbf84bbba30e69-405172d16eaff8798d", "stdout_lines": ["Extracting image from this script and loading into docker daemon, this step can take a few minutes", "dcos-genconf.cfccfbf84bbba30e69-405172d16eaff8798d.tar", "Loaded image: mesosphere/dcos-genconf:cfccfbf84bbba30e69-405172d16eaff8798d"], 

List cannot contain duplicates, I will tried ansible_eth1 now, and see if that works, I believe it should.

**Comment by kenadet** [comment]
`eth0` worked, but now the error is about master list containing duplicates

**Comment by andrewrothstein** [comment]
dunno. try with a couple of disposable VMs, perhaps vagrant + virtualbox, to get comfortable with the  playbook.

**Comment by kenadet** [comment]
Thanks, I actually started with some new errors: 

====> 192.168.1.214:22 FAILED
     TASK:
/usr/bin/ssh -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oBatchMode=yes -oPasswordAuthentication=no -p22 -i genconf/ssh_key -tt vagrant@192.168.1.214 sudo mkdir -p /opt/dcos_install_tmp
     STDERR:
          Permission denied (publickey,password).
     STDOUT:

Perhaps I open a new issue for that.
